// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ8HBFJ7k2jX4AsCtRn7Kf8Rh040dLu8A',
    appId: '1:379454219644:web:ba2721d23c83bee53870f9',
    messagingSenderId: '379454219644',
    projectId: 'reemdatabase',
    authDomain: 'reemdatabase.firebaseapp.com',
    databaseURL: 'https://reemdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'reemdatabase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFI9ICH58se0xSvDuV9BBaa_ZkrX6jUys',
    appId: '1:379454219644:android:5f419fc7b7d123d63870f9',
    messagingSenderId: '379454219644',
    projectId: 'reemdatabase',
    databaseURL: 'https://reemdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'reemdatabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeHOFqk96iTD3hYa2pw8x5bqYU-MUNu9M',
    appId: '1:379454219644:ios:33174d77b581542c3870f9',
    messagingSenderId: '379454219644',
    projectId: 'reemdatabase',
    databaseURL: 'https://reemdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'reemdatabase.appspot.com',
    androidClientId: '379454219644-ed6lg95rcts753lvcjkme92123cmap6h.apps.googleusercontent.com',
    iosClientId: '379454219644-nkcdemgd131shtl2rb269jtods8e32h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafad1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeHOFqk96iTD3hYa2pw8x5bqYU-MUNu9M',
    appId: '1:379454219644:ios:33174d77b581542c3870f9',
    messagingSenderId: '379454219644',
    projectId: 'reemdatabase',
    databaseURL: 'https://reemdatabase-default-rtdb.firebaseio.com',
    storageBucket: 'reemdatabase.appspot.com',
    androidClientId: '379454219644-ed6lg95rcts753lvcjkme92123cmap6h.apps.googleusercontent.com',
    iosClientId: '379454219644-nkcdemgd131shtl2rb269jtods8e32h7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rafad1',
  );
}
